# -*- coding: utf-8 -*-
'''
A world-renowned pixel artist Fred Zuppa has recently produced several
masterpieces in the form of square raster images encoded on grayscale
pixels. The images he has drawn can take values from 0 to 255
inclusive. Unfortunately the famous works have been lost because his
hard disk (alas!) stopped working and obviously Fred is desperate.
Programs to recover them from the filesystem don't work unfortunately
and so Fred relies on his trusted computer scientist, who tells him:

  "Bro, in truth I say to you, if you remember the
   size of the images and the values of the pixels along with the
   particular properties of your images, then we can try to write a
   recursive generator that will produce all of them based on your
   your inputs, that way we can try to retrieve them!"

The next morning Fred is able to give the necessary information in the
form of:
   1. `D` integer parameter describing the size of the square image.
   2. `colors` a list of integers describing the colors of Fred's
      images.  Fred's colors are between 0, 255.  colors can therefore
      be [128, 0, 255] while it cannot be [-100, 999]
   3. A text `img_properties` describing the properties of his images.
      The text can describe no properties (empty string) or can describe
      a property related to the pattern to be found in the images.

      For example:

      If `img_properties` is empty then the images do not need to satisfy 
      any property. On the contrary, if `img_properties` is equal to
      'pattern_{type}_' then the images have to contain the pattern
       specified in the string.

      The type of patterns are the following four:
       a) 'pattern_diff_': it indicates that by taking
       arbitrarily a subimage of size equal to 2x2, the subimage
       must have all pixels of different colors.

                 valid        not valid
            |  96 | 255 |   |   0 | 255 |
            | 128 |   0 |   | 255 |  96 |
              

        b) 'pattern_cross_': it indicates that by taking
       arbitrarily a subimage of equal to 2x2 in Fred's images,
       this subimage must have pixels on the diagonal all equal
       and the pixels on the anti-diagonal all equal
       but the two diagonals must be different in colors.

               valid          not valid     not valid
            |  96 | 255 |   |  0 | 255 |   | 61 | 61 |
            | 255 |  96 |   | 96 |   0 |   | 61 | 61 |

       c) 'pattern_hrect_': If present, this indicates that by taking
       arbitrarily a subimage of dimension equal to 2x2 in Fred's
       images, this subimage must have the pixels on the rows all
       equal but adjacent rows of different colors.

                 valid       not valid        not valid
            |   0 |   0 |   | 255 | 255 |    | 43 | 43 |
            | 128 | 128 |   | 0   | 255 |    | 43 | 43 |

       d) 'pattern_vrect_': If present, this indicates that by taking
       arbitrarily a subimage of dimension equal to 2x2 in Fred's
       images, this subimage must have the pixels on the columns all
       equal but adjacent columns with different colors.

                valid         not  valid    not valid
             | 0 | 255 |     | 0  | 0  |    | 22 | 22 |
             | 0 | 255 |     | 0  | 255|    | 22 | 22 |


Implement the recursive function or one that uses recursive methods:

      images = ex(colors, D, img_properties)

which takes as input the list of colors `colors`, the dimension of the
images `D` and a string `img_properties` which describes their
properties and recursively generates all images following the above
properties.  The function must return the enumeration of all valid
images as a list of images. Each image is a tuple of tuples where each
gray intensity is an integer. The order in which the images are
generated does not matter.

     Example: 2x2 image of zeros (all black) is:
         img = ( (0, 0), (0, 0), )

The timeout for each test is 1 second.

***
It is strongly advised to model the problem as a game tree, making
an effort to propagate only the necessary "moves" in the recursion and
thus construct an efficient solution. Alternatively, you can try to
"prune" the tree as soon as possible when building your solution.
***


You can view all images to be generated by invoking

     python test_01.py data/images_data_15.json

this saves all the expected images for test 15 images to disk and
creates an HTML file named `images_data_15.html` in the root directory
of the HW. You can view the images by opening the html file with a web
browser.
'''


def ex(colors, D, img_properties):
    # insert here your code
    pass


if __name__ == '__main__':
    # add here your test cases
    pass
